# Generated by Django 5.0.4 on 2025-09-27 17:08

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'Обрабатывается'), ('assembling', 'Собирается'), ('delivering', 'Доставляется'), ('ready', 'Готов')], default='created', max_length=20)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('volume_type', models.CharField(choices=[('single', 'Единичный'), ('multiple', 'Множественный')], max_length=20, verbose_name='Тип объёма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание (для единичного)')),
                ('document', models.FileField(blank=True, null=True, upload_to=orders.models.user_document_path, verbose_name='Документ (для множественного)')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество (для множественного)')),
                ('ready_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата готовности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_date'],
            },
        ),
    ]
